# Generated by Django 4.1 on 2022-09-21 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='filmWatchlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('watchedmovies', models.BooleanField()),
                ('titlemovie', models.TextField()),
                ('ratingmovie', models.IntegerField()),
                ('moviereleasedate', models.TextField()),
                ('reviewmovie', models.TextField()),
            ],
        ),
    ]
